class BibleConstants {
  static const List<String> oldTestamentOrderEn = [
    'Genesis',
    'Exodus',
    'Leviticus',
    'Numbers',
    'Deuteronomy',
    'Joshua',
    'Judges',
    'Ruth',
    '1 Samuel',
    '2 Samuel',
    '1 Kings',
    '2 Kings',
    '1 Chronicles',
    '2 Chronicles',
    'Ezra',
    'Nehemiah',
    'Esther',
    'Job',
    'Psalms',
    'Proverbs',
    'Ecclesiastes',
    'Song of Solomon',
    'Isaiah',
    'Jeremiah',
    'Lamentations',
    'Ezekiel',
    'Daniel',
    'Hosea',
    'Joel',
    'Amos',
    'Obadiah',
    'Jonah',
    'Micah',
    'Nahum',
    'Habakkuk',
    'Zephaniah',
    'Haggai',
    'Zechariah',
    'Malachi',
  ];

  static const List<String> newTestamentOrderEn = [
    'Matthew',
    'Mark',
    'Luke',
    'John',
    'Acts',
    'Romans',
    '1 Corinthians',
    '2 Corinthians',
    'Galatians',
    'Ephesians',
    'Philippians',
    'Colossians',
    '1 Thessalonians',
    '2 Thessalonians',
    '1 Timothy',
    '2 Timothy',
    'Titus',
    'Philemon',
    'Hebrews',
    'James',
    '1 Peter',
    '2 Peter',
    '1 John',
    '2 John',
    '3 John',
    'Jude',
    'Revelation',
  ];

  static const List<String> oldTestamentOrderSw = [
    'Mwanzo',
    'Kutoka',
    'Mambo ya Walawi',
    'Hesabu',
    'Kumbukumbu la Torati',
    'Yoshua',
    'Waamuzi',
    'Ruthu',
    '1 Samueli',
    '2 Samueli',
    '1 Wafalme',
    '2 Wafalme',
    '1 Mambo ya Nyakati',
    '2 Mambo ya Nyakati',
    'Ezra',
    'Nehemia',
    'Esta',
    'Ayubu',
    'Zaburi',
    'Mithali',
    'Mhubiri',
    'Wimbo Ulio Bora',
    'Isaya',
    'Yeremia',
    'Maombolezo',
    'Ezekieli',
    'Danieli',
    'Hosea',
    'Yoeli',
    'Amosi',
    'Obadia',
    'Yona',
    'Mika',
    'Nahumu',
    'Habakuki',
    'Sefania',
    'Hagai',
    'Zekaria',
    'Malaki',
  ];

  static const List<String> newTestamentOrderSw = [
    'Mathayo',
    'Marko',
    'Luka',
    'Yohana',
    'Matendo ya Mitume',
    'Warumi',
    '1 Wakorintho',
    '2 Wakorintho',
    'Wagalatia',
    'Waefeso',
    'Wafilipi',
    'Wakolosai',
    '1 Wathesalonike',
    '2 Wathesalonike',
    '1 Timotheo',
    '2 Timotheo',
    'Tito',
    'Filemoni',
    'Waebrania',
    'Yakobo',
    '1 Petro',
    '2 Petro',
    '1 Yohana',
    '2 Yohana',
    '3 Yohana',
    'Yuda',
    'Ufunuo wa Yohana',
  ];
}
